// Mocks generated by Mockito 5.4.4 from annotations
// in send_money_app_test/test/presentation/blocs/transactions/transactions_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:send_money_app_test/domain/entities/transaction.dart' as _i5;
import 'package:send_money_app_test/domain/repositories/transaction_repository.dart'
    as _i2;
import 'package:send_money_app_test/domain/use_cases/get_transactions.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTransactionRepository_0 extends _i1.SmartFake
    implements _i2.TransactionRepository {
  _FakeTransactionRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTransactions].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTransactions extends _i1.Mock implements _i3.GetTransactions {
  MockGetTransactions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TransactionRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTransactionRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TransactionRepository);

  @override
  _i4.Future<List<_i5.Transaction>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.Transaction>>.value(<_i5.Transaction>[]),
      ) as _i4.Future<List<_i5.Transaction>>);
}
